### ISSUE TITLE
Cleanup docs

### ISSUE THREAD

**Issue by turtlemonvh** [turtlemonvh/ionic-spark-utils#16]
In addition to documentation in the README, I need to clean up the JavaDoc/ScalaDoc comments in the code so the generated documentation is cleaner.

Link to these generated docs on https://javadoc.io/ or similar.

**Comment by turtlemonvh** [comment]
I've been fiddling with this, esp. trying to get docs for java sources since most of the project is java code.

Unfortunately this is not possible until Scala 2.12:

* bug: https://github.com/scala/bug/issues/11365
* announcement of fix: https://www.scala-lang.org/news/2.12.0/#scaladoc-can-be-used-to-document-java-sources

I was thinking about breaking this down into a separate library for the java sources, and that is looking like a better option now.

**Comment by r0bb23** [comment]
> I've been fiddling with this, esp. trying to get docs for java sources since most of the project is java code.
> 
> Unfortunately this is not possible until Scala 2.12:
> 
> * bug: [scala/bug#11365](https://github.com/scala/bug/issues/11365)
> * announcement of fix: https://www.scala-lang.org/news/2.12.0/#scaladoc-can-be-used-to-document-java-sources
> 
> I was thinking about breaking this down into a separate library for the java sources, and that is looking like a better option now.

Hey Timothy,
The newer versions of spark use Scala 2.12.

It was added experimentally in 2.4 and will be default in 3. I've switched my project over to it.

**Comment by turtlemonvh** [comment]
Ah ok cool - I'll try that then!

I was looking at this as an alternative: https://github.com/lightbend/genjavadoc

But honestly not excited about something with so many sbt options. I am trying to spend as little time as possible messing around with sbt. Every time I try to do something simple it seems to take hours to get it to behave.

**Comment by r0bb23** [comment]
Yeah. Sbt is the personification of Scala. Hard to learn but great once you know it. I would still rather use sbt and Scala over any other choices in the Java world. Though I would also prefer just not to be the Java world.

**Comment by turtlemonvh** [comment]
The switch to 2.12 made this much easier (code on #22).

I need to fiddle around a bit more to [make cross compiling behave](https://www.scala-sbt.org/1.x/docs/Cross-Build.html), but since the code is the same for 2.11 and 2.12 (and Spark is recommending 2.12 now) I'm not going to fight with sbt to make the docs work on 2.11.

**Comment by turtlemonvh** [comment]
Docs for 0.0.2 published as part of #21 
https://oss.sonatype.org/service/local/repositories/releases/archive/io/github/turtlemonvh/ionicsparkutils_2.12/0.0.2/ionicsparkutils_2.12-0.0.2-javadoc.jar/!/io/github/turtlemonvh/ionicsparkutils/index.html
